Switching the Asmtools version from 7.0 to 8.0 (#62)
* Update LICENSE file

* The experimental version is aimed to refactor the tool

* verificationType mistakenly added to source code is renamed to type

* Adapted mvn bindings to at8

* Added tests to represent bad stream handling in jdec and correctone in jdis

* Made jdec to write output to proper toolOutput instead of bad logOutput

* 7903208: [Jasm] Add support for generics (the Signature attribute)

* 7902888: Excess entries in BootstrapMethods with the same bsm, bsmKind, bsmArgs

* Replaced hardcoded String[] args, by varargs String... where reasonable

Once the "tool" mandatory array memebr was removed from each tool's main
method, and considering calls from libraries, and form tests where the
argument is very often just one file, or more readable "a1", a2"...
without new String[]{} declaration, changed those String[] enforcing
headers to more benevolent String...

* Intentionally removed ACC_SUPER class modifier was causing hotswap to fail

When jasm's  disasm, modify, asm cycle output binary was used for class
hotswap, remote JDK was not accepting it with java.lang.UnsupportedOperationException:
class redefinition failed: attempted to change the class modifiers
beacuse of ommited supoer keyword (although it have already no real
reason)

This patch is returning the kwyword without conditions, when it was
included in original bytecode

* extended test to verify that super is not used always

if super is not in source code, then it is not in disambled code

* 7903248: jasm: FieldData.ConstantValue holds undefined reference to CP while writing fields to a class

* Added support for stdin in jdis

* stdin is now read also by jasm,jcod,jdec

more tests needed

* Removed jdis specific missleading provide method

* Tool output moved where it belongs to commons

* Removed duplicated declaration of ArrayList<ToolInput> fileList

* Changed requireNonNull message in getDataInputStream

* Added one more abstraction layer providing highly reusable byte[] based input

* Properly exiting after verson is printed

* Stream based inputs are now drained once needed, not during construction

* reworked stdin read to be initiated by -

As a side effect, files and stdin can be read together
remove dduplicated code in tests by getting class in compile time
added tests and adapted older to new behavior

* added tests if asmtools assmble itself into valid bytecode

Added two set of tests
jdec->jcoder->load
jdis->jasm->load
Both in two variants, with -g, and without

Both jdec->jcoder->load works fine
Both jdis->jasm->load now fails on three files from 278:
 /org/openjdk/asmtools/jasm/JasmEnvironment$InputFile.class, /org/openjdk/asmtools/jcoder/Jcoder.class, /org/openjdk/asmtools/jasm/Parser.class
Fail looks valid.

Unluckily, the issue where -g disassembled and back assembled
com.google.gson.Gson produce invalid bytecode was not hit

The class BruteForceHelper is reusable for any set of classes

* Naive fix for enforced dot.suffix

* repalce stdout by configurable object

This checkout is not buildable, but server as showcase for issue with
dual logging for compilers

* Replaced dualstream logger by wrapper

so it can  be later made fully customisable

* Enabled shared i18n properties via reused asmtools/i18n.props

* All four tools now use neww ToolOutput output

As a consequence, all four tools by by default prints to stdout, and
honours -d properly

* Fixed typo which casued behavior regression

found by unittests

* Refatoed tests so they can harbour resources in maven way

* Moved all logging to stderr. use -dls to return original behavior

The -dls switch  is oging to be removed once stderr is properl adapted

* Implemented library-like input and output

This commit is adding byte[]/String  input/output clasases for direct
library usage.
Added tests, advertising how simple is usage of those inputs/outputs

There are two hunks, which fixes issues ovberlooked in previous
refactorings:
 - traceln now correctly calls getOutputs
 - jdec now uses proper logger insted of accidental stderr

* Enabled -g for jcoder to be set from external code

* Temporary workaround around tests being order-sensitive

As -g is now making some disassmebld code not asemble-able back, and
order of tests is not deterministic, and Options are static, thus if -g
is now set in some test, it is not unset in other tests.

Real fix is to move Options out of static context to context of
environment as it is done for jcoder.

* Added github actions

Just for record for "act" for local testing. To run with podman based distros, several steps are ncessary. See https://github.com/nektos/act/issues/303 ; especially
 * https://github.com/nektos/act/issues/303#issuecomment-937698375
 *  and https://github.com/nektos/act/issues/303#issuecomment-962403508
    *   the bind and socket
eg:
 systemctl enable --now --user podman.socket
 systemctl start --user podman.socket
 export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock
 ../act/bin/act   --bind --container-daemon-socket $XDG_RUNTIME_DIR/podman/podman.sock

 To rerun the build on clean env, you have to stop and start the podman socket again

Without explicit 'mvn test' the tests are not running. Not sure why

* 7902888: Excess entries in BootstrapMethods with the same bsm, bsmKind, bsmArgs

* Fixed issue when jasm produced only one file from source with multiple ones

Added tests for this issue
Added test veryfying that the jcoder is not affected

* 7903401: jtreg fails if set of jdk tests process jasm,jdis files with defects

* 7903402: jdis: tool writes incorrect StackMapTable if the first same_frame has type 0 (#51)

* 7902888: Excess entries in BootstrapMethods with the same bsm, bsmKind, bsmArgs

* 7903401: jtreg fails if set of jdk tests process jasm,jdis files with defects

* 7903402: jdis: tool writes incorrect StackMapTable if the first same_frame has type 0

* 7902888: Excess entries in BootstrapMethods with the same bsm, bsmKind, bsmArgs

* Refactored new ToolInput/Outputs so they reside in own packages and not in original interfaces (#53)

* Refactored new ToolInput/Outputs so they reside in own packages and not in original interfaces

* Removed unused imports

* Added licence headers

* Added ajvadoc description to three main interfaces.

* Removed unnecessary guard condition before changging \ to / for fqn

* Replaced "\n" by System.lineSeparator()

* Used better names for highlighted abbrevations

* 7903405: compiler does not warn about instruction arguments that exceed allowed limits (#54)

* 7902888: Excess entries in BootstrapMethods with the same bsm, bsmKind, bsmArgs

* 7903401: jtreg fails if set of jdk tests process jasm,jdis files with defects

* 7903402: jdis: tool writes incorrect StackMapTable if the first same_frame has type 0

* 7902888: Excess entries in BootstrapMethods with the same bsm, bsmKind, bsmArgs

* 7903405: compiler does not warn about instruction arguments that exceed allowed limits

* 7903405: compiler does not warn about instruction arguments that exceed allowed limits

* Delete ToolOutput.java

* Fixed junit test for CODETOOLS-7903405 (#56)

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0 (#57)

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* Fix tabs

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0 (Part II) (#58)

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* Fix tabs

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* CODETOOLS-7903506: Asmtools: jdis prints BootstrapMethod attribute if detailed output is off (#59)

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* Fix tabs

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* 7903506: Asmtools: jdis prints BootstrapMethod attribute if detailed output is off

* 7903509: jcoder, jasm: add option to override class file version in source file(s) (#60)

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* Fix tabs

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* 7903509: jcoder, jasm: add option to override class file version in source file(s)

* CODETOOLS-7903531: jdis: Suppress printing comments by adding an option (#61)

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* Fix tabs

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* 7903458: Umbrella: Preparations for switching to Asmtools 8.0

* 7903531: jdis: Suppress printing comments by adding an option

---------

Co-authored-by: Jiri Vanek <jvanek@redhat.com>